// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxbQ6tCYlnzxInJoeNsfHzXCRmzbrPtKI',
    appId: '1:804723477649:web:2f5646d88de01cd0228330',
    messagingSenderId: '804723477649',
    projectId: 'robot-503ae',
    authDomain: 'robot-503ae.firebaseapp.com',
    storageBucket: 'robot-503ae.appspot.com',
    measurementId: 'G-WJEXVZBZ3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBln9W9-kdze08eV8eSisBBJaQiijaJ5Uw',
    appId: '1:804723477649:android:958e6627fe563979228330',
    messagingSenderId: '804723477649',
    projectId: 'robot-503ae',
    storageBucket: 'robot-503ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5yoFShfXtLRlA8rH0jivbzhZZtNrlois',
    appId: '1:804723477649:ios:c67c3505d5c260fe228330',
    messagingSenderId: '804723477649',
    projectId: 'robot-503ae',
    storageBucket: 'robot-503ae.appspot.com',
    iosBundleId: 'com.example.simpleSurvey',
  );
}
